# Analysis of longitudinal data #

## Data wrangling ##

https://github.com/shinyk0514/IODS-project/blob/master/data/meet_and_repeat.R


## Data analysis ##

### Analysis using RATS ###


#### Reading RATS ####
```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
ratsl <- read.csv(file = "C:\\Users\\Young Shin\\Documents\\IODS-project\\data\\ratslong.csv", row.names = 1)
```



#### Individuals on the plot with standardized values ####
```{r}
ratsl$Group <- factor(ratsl$Group)
ratsl$ID <- factor(ratsl$ID)

ratsl <- ratsl %>% group_by(Time) %>% mutate(stweight = (Weight - mean(Weight)) / sd(Weight)) %>% ungroup()

ggplot(ratsl, aes(x = Time, y = Weight, linetype = ID)) + geom_line() + facet_grid(. ~ Group, labeller = label_both) + scale_linetype_manual(values = rep(1:6, times=4)) + theme(legend.position = "none") +   scale_y_continuous(limits = c(min(ratsl$Weight), max(ratsl$Weight)))
```


#### Summary graphs ####
```{r}
n <- ratsl$Time %>% unique() %>% length()

rats_s <- ratsl %>% group_by(Group, Time) %>% summarise(mean = mean(Weight), se = ( sd(Weight) / sqrt(n) )) %>% ungroup()
glimpse(rats_s)

ggplot(rats_s, aes(x = Time, y = mean, linetype = Group, shape = Group)) +
  geom_line() +
  scale_linetype_manual(values = c(1,2,3)) +
  geom_point(size=3) +
  scale_shape_manual(values = c(1,2,3)) +
  theme(legend.position = c(0.9,0.5)) +
  scale_y_continuous(name = "mean(Weight) +/- se(Weight)")

ggplot(ratsl, aes(x=factor(Time), y=Weight, fill=Group)) + geom_boxplot()
```


#### Creating summary data with mean ####
```{r}
ratsl8s <- ratsl %>%
  filter(Time > 0) %>%
  group_by(Group, ID) %>%
  summarise(mean=mean(Weight)) %>%
  ungroup()
glimpse(ratsl8s)
ggplot(ratsl8s, aes(x=Group, y = mean)) + geom_boxplot() + stat_summary(fun.y = "mean", geom = "point", shape=23, size=4, fill = "white") + scale_y_continuous(name = "mean(rats) +/- se(rats)")
```


#### Creating new data by filtering the outlier ####
```{r}
glimpse(ratsl8s)
ratsl8s1 <- filter(ratsl8s, Group==1 & mean>260 | Group==2 & mean<550 | Group==3 & mean>500)
ggplot(ratsl8s1, aes(x=Group, y = mean)) + geom_boxplot() + stat_summary(fun.y = "mean", geom = "point", shape=23, size=4, fill = "white")
```


#### ANOVA ####
```{r}
str(ratsl)
ratsl8s2 <- ratsl8s %>%
  mutate(baseline = ratsl$WD1)
fit <- lm(mean ~ baseline + Group, data = ratsl8s2)
anova(fit)

```


### Analysis using BPRS ###

