# Regression and model validation #

*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods.
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using.


*To conduct data wrangling, I read the full learning2014 data and explored the structur and dimentions of the data by using the following codes.*

## Data wrangling ##
lrn14 <- read.table("http://www.helsinki.fi/~kvehkala/JYTmooc/JYTOPKYS3-data.txt", sep="\t", header=TRUE)

dim(lrn14)

str(lrn14)

*To create a dataset for analysis, I first scaled all combination variables. After that, I kept only columns required for anlaysis, excluded unsuitable cases and modified column names by using the following codes.* 

### Scaling variables to the original scales ###
lrn14$Attitude / 10
lrn14$attitude <- lrn14$Attitude / 10

library(dplyr)

deep_questions <- c("D03", "D11", "D19", "D27", "D07", "D14", "D22", "D30","D06",  "D15", "D23", "D31")
surface_questions <- c("SU02","SU10","SU18","SU26", "SU05","SU13","SU21","SU29","SU08","SU16","SU24","SU32")
strategic_questions <- c("ST01","ST09","ST17","ST25","ST04","ST12","ST20","ST28")

deep_columns <- select(lrn14, one_of(deep_questions))
lrn14$deep <- rowMeans(deep_columns)

surface_columns <- select(lrn14, one_of(surface_questions))
lrn14$surf <- rowMeans(surface_columns)

strategic_columns <- select(lrn14, one_of(strategic_questions))
lrn14$stra <- rowMeans(strategic_columns)

### Keeping columns needed for analysis ###
keep_columns <- c("gender", "Age", "attitude", "deep", "stra", "surf", "Points")
learning2014 <- select(lrn14, one_of(keep_columns))
str(learning2014)

### Modifying column names ###
colnames(learning2014)[2] <- "age"
colnames(learning2014)[7] <- "points"
learning2014 <- filter(learning2014, points > 0)

str(learning2014)

 

*To fit regression models, I read and explore the data set as follows:*
## Data analysis ##
ex2 <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", sep=",", header=TRUE)

### Exploring data ###
str(ex2)
dim(ex2)

*The structure of the data is as follows: The number of observations is 166 and the number of varaibles is 7.*
> str(ex2)
'data.frame':	166 obs. of  7 variables:
 $ gender  : Factor w/ 2 levels "F","M": 1 2 1 2 2 1 2 1 2 1 ...
 $ age     : int  53 55 49 53 49 38 50 37 37 42 ...
 $ attitude: num  3.7 3.1 2.5 3.5 3.7 3.8 3.5 2.9 3.8 2.1 ...
 $ deep    : num  3.58 2.92 3.5 3.5 3.67 ...
 $ stra    : num  3.38 2.75 3.62 3.12 3.62 ...
 $ surf    : num  2.58 3.17 2.25 2.25 2.83 ...
 $ points  : int  25 12 24 10 22 21 21 31 24 26 ...
> dim(ex2)
[1] 166   7

*I created plots showing the distributions of the variables and the relationships between them by using the following codes. According to the plot and summary information, "points" is most highly correlated with "attitude", whereas it is least correlated with "deep".*  

### Graphical overview and summaries ###
library(ggplot2)
ggplot(ex2)
pairs(ex2[-1])

library(GGally)
library(ggplot2)

p <- ggpairs(ex2, mapping = aes(), lower = list(combo = wrap("facethist", bins = 20)))
p

summary(ex2)
> str(ex2)
'data.frame':	166 obs. of  7 variables:
 $ gender  : Factor w/ 2 levels "F","M": 1 2 1 2 2 1 2 1 2 1 ...
 $ age     : int  53 55 49 53 49 38 50 37 37 42 ...
 $ attitude: num  3.7 3.1 2.5 3.5 3.7 3.8 3.5 2.9 3.8 2.1 ...
 $ deep    : num  3.58 2.92 3.5 3.5 3.67 ...
 $ stra    : num  3.38 2.75 3.62 3.12 3.62 ...
 $ surf    : num  2.58 3.17 2.25 2.25 2.83 ...
 $ points  : int  25 12 24 10 22 21 21 31 24 26 ...
> dim(ex2)
[1] 166   7
> library(ggplot2)
> ggplot(ex2)
> pairs(ex2[-1])
> summary(ex2)
 gender       age           attitude          deep            stra      
 F:110   Min.   :17.00   Min.   :1.400   Min.   :1.583   Min.   :1.250  
 M: 56   1st Qu.:21.00   1st Qu.:2.600   1st Qu.:3.333   1st Qu.:2.625  
         Median :22.00   Median :3.200   Median :3.667   Median :3.188  
         Mean   :25.51   Mean   :3.143   Mean   :3.680   Mean   :3.121  
         3rd Qu.:27.00   3rd Qu.:3.700   3rd Qu.:4.083   3rd Qu.:3.625  
         Max.   :55.00   Max.   :5.000   Max.   :4.917   Max.   :5.000  
      surf           points     
 Min.   :1.583   Min.   : 7.00  
 1st Qu.:2.417   1st Qu.:19.00  
 Median :2.833   Median :23.00  
 Mean   :2.787   Mean   :22.72  
 3rd Qu.:3.167   3rd Qu.:27.75  
 Max.   :4.333   Max.   :33.00 




*To begin with, I chose "attitude", "stra" and "surf" as explanatory variables and fitted a regression model(model1) with them as follows. However, as the coefficient of surf is not significant and its p-value is too high, I fitted another model(model2) withouth the variable. In model2, attitude and stra have an positive effect on points. The coefficient of attitude is significant at the 0.001% significance level and that of stra is significant at the 10% significance level. Regarding R-squrare, model2's adjusted R-square is 0.1951, which is a bit higher than model1's one accounting for 0.1927.*

### Fitting regression models ###
### explanatory variables: attitude, stra, surf
model1 <- lm(points ~ attitude + stra + surf, data = ex2)
summary(model1)
model2 <- lm(points ~ attitude + stra, data = ex2)
summary(model2)

> model1 <- lm(points ~ attitude + stra + surf, data = ex2)
> summary(model1)
Call:
lm(formula = points ~ attitude + stra + surf, data = ex2)
Residuals:
     Min       1Q   Median       3Q      Max 
-17.1550  -3.4346   0.5156   3.6401  10.8952 
Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  11.0171     3.6837   2.991  0.00322 ** 
attitude      3.3952     0.5741   5.913 1.93e-08 ***
stra          0.8531     0.5416   1.575  0.11716    
surf         -0.5861     0.8014  -0.731  0.46563    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Residual standard error: 5.296 on 162 degrees of freedom
Multiple R-squared:  0.2074,	Adjusted R-squared:  0.1927 
F-statistic: 14.13 on 3 and 162 DF,  p-value: 3.156e-08

> model2 <- lm(points ~ attitude + stra, data = ex2)
> summary(model2)
Call:
lm(formula = points ~ attitude + stra, data = ex2)
Residuals:
     Min       1Q   Median       3Q      Max 
-17.6436  -3.3113   0.5575   3.7928  10.9295 
Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   8.9729     2.3959   3.745  0.00025 ***
attitude      3.4658     0.5652   6.132 6.31e-09 ***
stra          0.9137     0.5345   1.709  0.08927 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
Residual standard error: 5.289 on 163 degrees of freedom
Multiple R-squared:  0.2048,	Adjusted R-squared:  0.1951 
F-statistic: 20.99 on 2 and 163 DF,  p-value: 7.734e-09


*I created diagnostic plots including Residuals vs Fitted values, Normal QQ-plot and Residuals vs Leverage as follows:*
### Producing diagnostic plots ###
#### Residuals vs Fitted Values, Normal QQ-plot and Residuals vs Leverage ####
par(mfrow = c(2,2))
plot(model2, which = c(1,2,5))